global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: app
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8080"]
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
